#+TITLE: managing accounts on 9front
#+SETUPFILE: setupfile.org

this assumes you are using hjfs in a [[./9front-cpusetup.org][cpu setup]] (ie with a fileserver
and auth). if you are using cwfs, you should be able to just replace
~/srv/hjfs.cmd~ with ~/srv/cwfs.cmd~ for most of it.

#+TOC: headlines 3

* creating accounts
#+begin_example
echo newuser bob >> /srv/hjfs.cmd
#+end_example
will create a user named ~bob~

use ~auth/keyfs~ to mount the authentication database, then set a
password and enable the account

#+begin_example
auth/keyfs
auth/changeuser bob
auth/enable bob
#+end_example

[2023-08-27 Sun]: mkf recommends filling in the email-related fields,
as some programs use them

** adding a user to a group
#+begin_example
echo newuser upas +bob >> /srv/hjfs.cmd
#+end_example
will add ~bob~ to the ~upas~ group, which allows mail. the ~adm~ and
~sys~ groups allow adding users and accessing system files
respectively. there is also ~cron~ for allowing recurring tasks.

* renaming users
#+begin_example
echo newuser bob jane >> /srv/hjfs.cmd
#+end_example

to rename ~bob~ to ~jane~. you will also need to set a new password
for them in the auth server.

#+begin_example
auth/changeuser jane
#+end_example

* setup defaults

run ~/sys/lib/newuser~ as the new user to get the default profile and
stuff in your home directory

