#+TITLE: about
#+SETUPFILE: setupfile.org

after reading some of [[https://100r.co][100 rabbits]]' work, i realized that i depend on
being always-online too much.

this was created to potentially replace my old [[https://wiki.owen.bellz.org][pmwiki wiki]]. pmwiki
does not really have any good solutions for working offline, the
closest thing being [[https://www.pmwiki.org/wiki/Cookbook/WikiOnAStick][wiki on a stick]], which literally runs a webserver
with a LAMP stack from a non-portable[fn:1:non-portable as in being
difficult to run on other operating systems. in physical space, its
still very portable.] exe file. yuck.

i was also considering using [[https://vimwiki.github.io][vimwiki]], which has a more wiki-like
syntax, however that also makes the syntax less consistent and harder
to convert to/from. also configuring vimwiki is somewhat a nightmare
(perhaps ive been spoiled by lisp's customizability) and it seems a
bit overbearing about how it manages files.

* setupfile

the [[./setupfile.org][setupfile]] is largely based on [[https://yeti.tilde.institute/brain/][yeti's brain's setupfile]]. i know you
will probably never read this, but thank you for letting me use it :3

* contributing

the git repository for this wiki is available in [[https://owen.bellz.org/git/orgwiki/][several]] [[https://git.sr.ht/~xfnw/orgwiki][different]]
[[https://github.com/xfnw/orgwiki][places]].

send a [[https://git-send-email.io][patch]] to ~xfnw ate riseup doot net~ (replacing ~ate~ and ~doot~
with the at and the full stop symbol respectively). hopefully i'll get
a mailinglist setup Soon\trade.

if you do not want to send a patch, you can instead open a pull
request on [[https://github.com/xfnw/orgwiki/pulls][github]].

** TODO style guide

** licensing

actual content is licensed under a [[https://creativecommons.org/licenses/by-nc-sa/4.0/][CreativeCommons
Attribution-NonCommercial-ShareAlike 4.0 International]] license.

additional content not subject to this license may be included in the
~media/~ directory, on the condition that distribution with this wiki
falls under fair use. if you, in good faith, believe content you own
was included there not under fair use, please send an email to the
above address.
