#+TITLE: iproute2
#+SETUPFILE: setupfile.org

iproute2, better known as the ~ip~ command, is a replacement for the
old ~route~ and ~ipconfig~ utilities.

it lets you abbreviate subcommands, ie ~ip route~ -> ~ip r~, ~ip
address~ -> ~ip a~.

* routes
#+begin_example
ip r
#+end_example
will list the current routes.

add ~-6~ to show for ipv6
#+begin_example
ip -6 r
#+end_example

** adding a route
#+begin_example
ip r add default via 192.168.1.1
#+end_example
adds a ~default~ route to a gateway at ~192.168.1.1~. a CIDR can be
used instead of ~default~. ~default~ is roughly equivalent to a
~0.0.0.0/0~ or a ~::/0~ route.

~dev devicename~ can be added to restrict it to ~devicename~.

there are also ~blackhole~ routes, that just eats stuff
#+begin_example
ip r add blackhole 31.13.66.35
#+end_example

** deleting a route
#+begin_example
ip r del default
#+end_example
will delete the default route.

* addresses
#+begin_example
ip a
#+end_example
will list the addresses and status of your networking devices.

** adding an address
#+begin_example
ip a a 127.6.2.1/32 dev lo
#+end_example
adding more specific loopback addresses is useful for making programs
that do not allow configuring this bind to a different ip, for example
changing the source for clients using a tor hidden service on irc

** down/up
#+begin_example
ip link set wlan0 up
#+end_example
will set device ~wlan0~ up.
