#+TITLE: powdertoy
#+SETUPFILE: setupfile.org
#+OPTIONS: ^:{}

[[https://powdertoy.co.uk/][the powder toy]] is a 2D sandbox simulation thing

* magic values

** deut life max amount
deut life is a weird signed number, theoretically this is the max
amount before it overflows to negative. oddly this does not line up
with either a power of two or half a power of two.

calculated on [2023-01-15 Sun][fn:1: a previous calculation on
[2021-03-12 Fri] thought it was ~530584300921369395~, but this seems
to no longer be the case], the value is ~530884300967510015~

** welding temp for iron
this melts it but will get quickly conducted away

~1700~ with the property editing tool, presumably in celsius

* commands
the console may be entered by pressing the ~`~ (backtick) key.

** pressure
#+begin_example
tpt.set_pressure(nil,nil,nil,nil,200)
#+end_example

will set the pressure to 200, everywhere

** loadfile
the loadfile command will load a lua file, relative to your data
directory, and creates an anonymous function.

#+begin_example
loadfile("cat.lua")()
#+end_example

adding a ~()~, optionally putting in arguments, will call the function
